### ISSUE TITLE
Overleaf bugs

### ISSUE THREAD

**Issue by dpicca** [Journal-of-CLS/JCLS-Template#8]
Hi!
It would appear that your template has some compilation problems on Overleaf. I will put the attached log to highlight the problems. 

Could you, please tell me how to debug it?

Many thanks

[output (2).log](https://github.com/Journal-of-CLS/JCLS-Template/files/13473809/output.2.log)

**Comment by gerstorfer** [comment]
You need to use lualatex instead of pdflatex
