### ISSUE TITLE
Fußzeile mit volume und issue number

### ISSUE THREAD

**Issue by christofs** [Journal-of-CLS/JCLS-Template#9]
Die Fußzeile im Template sollte (für das aktuelle Heft) so aussehen: 
`JCLS 2 (1), 2023, 10.48694/jcls.9999`
Also in der Struktur: 
`JCLS [volume] ([issue]), [jahr], [DOI]` 
Die Infos dafür sollten in `self.bib` liegen, oder?

**Comment by gerstorfer** [comment]
Das ist schon implementiert und muss in `metadata/article.tex` eingetragen werden:

```
% information provided by the editors

\article{
datereceived = 2023-xx-xx,
dateaccepted = 2023-xx-xx,
datepublished = 2023-xx-xx,
doi = {10.48694/jcls.999},
articletype = under review,
volume = 2,
issuenumber = 1,
issuenote = {This paper has been submitted to the conference track of JCLS. },
reviewers = {tbc},
}
```

Wenn `volume` in Block Citation auftauchen soll, muss die Info auch in `metadata/self.bib` eingetragen werden:

```
@article{self,
  author = {},
  date = {2023},
  doi = {10.48694/jcls.xxx},
  volume = {1},
  issue = {1},
  journaltitle = {Journal of Computational Literary Studies},
  title = {Unnecessarily Complicated Research Title},
  subtitle = {},
  options = {skipbib=true},
}
```

**Comment by gerstorfer** [comment]
Ich habe das template für `metadata/self.bib` aktualisiert

**Comment by christofs** [comment]
Hi Dominik, muss es doch nochmal aufmachen, wegen zwei Fragen: 

1. Müssen / sollten die Metadate in `article.tex` als ein Block eingefügt werden `\article{}` ? Bisher waren das zeilenweise Einträge. 
2. Woher nimmt das Template die Information zum Jahr in der Fußzeile? Ideal wäre es, wenn wir das spezifizieren könnten. 

Hintergrund zu #2: Aktuell habe wir den Fall, dass Artikel im Januar / Februar 2024 erscheinen werden, die aber dem Issue "2 (1) 2023" zugehören. Das kann ich aber offenbar nicht steuern, es erscheint automatisch "2024" in der Fußzeile. Das passiert selbst dann, wenn ich als `datepublished` sowas wie `2023-12-31` eintrage (nicht nur, wie ich erst dachte, wenn ich dort ein Datum wie `2024-01-15` eintrage).

**Comment by gerstorfer** [comment]
1. Die Metadaten sollen in einem Block eigefügt werden
2. Es gibt ein neues Metadatenfeld `issueyear` das unabhängig von `datepublished` gesetzt werden kann

~~~
% information provided by the editors

\article{
	datereceived = 2021-xx-xx,
	dateaccepted = 2022-xx-xx,
	datepublished = 2024-xx-xx,
	doi = {10.48694/jcls.xxx},
	articletype = under review,
	volume = 1,
	issueyear = 2023,
	issuenumber = 1,
	issuenote = {This paper has been submitted to the conference track of JCLS. },
	reviewers = {tbc},
}
~~~
